### PR TITLE
Updated the initalization of the component to use the year provided by the defaultValue

### PR DESCRIPTION
**Pull request by mel-habip**
Previously, the Month was being updated but not the year, so now it is updated as well.

### CODE REVIEW

**Comment by mel-habip** [comment]
#5 should be fixed upon merge

**Comment by Lekhrajk** [comment]
is this fixed ? because i am also getting this issue year is 2022 by default

**Comment by mel-habip** [comment]
Still waiting for the owner to merge this. I forked the branch but wasn't able to get it to work locally, do you know if that's possible?

**Comment by mel-habip** [comment]
@agunbuhori it seems I'm not the only one needing this fix 😅 

You developed something beautiful really but it almost can't be used without this very tiny fix. Please let me know if there are any issues though 😃

**Comment by Lekhrajk** [comment]
i also tried changing locally but that did not work

**Comment by abhimanyu95** [comment]
@agunbuhori You need to build and publish the changes to npm.

**Pull request merged**
